### 다양한 패키지로 데이터 분석하기
> 데이터 분석을 통해 경제적 자유를 이루기 위한주식 및 부동산 자료분석까지 직접 해볼 수 있다.
  넘파이, 판다스, 맷플롯립을 활용해 데이터 분석을 해보자 

> 데디터 분석 패키지 준비하기
- 넘파이 : 배열계산기능, 반올림,버리기 기능  floor, ceil, power
- 판다스 : 데이터프레임으로 데이터입력, 가공  describe, groupby
- 맷플롯립 : 그래프 그리기  plot,hist,bar
- math, scipy, statsmodels

> 넘파이로 배열다루기
- 넘파이는 배열을 다루는 도구이며 숫자로 된 큰 배열 데이터를 다룰 때 진가를 발휘합니다.
- 넘파이로 배열 정의하

In [2]:
# 넘파이로 배열 정의하기
import numpy as np
a= np.array([[2,3],[5,2]])
a



array([[2, 3],
       [5, 2]])

In [3]:
#배열 슬라이싱하기
d = np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9],[8,9,10,11,11]])
d

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  5,  6,  7],
       [ 5,  7,  8,  9,  9],
       [ 8,  9, 10, 11, 11]])

In [4]:
d[1][2]
d[1,2]

5

In [5]:
d[1:,3:]

array([[ 6,  7],
       [ 9,  9],
       [11, 11]])

In [6]:
# 배열의 크기 알아내기 : shape
d.shape
d= np.array([2,3,4,5,6])
d
d.shape

(5,)

In [7]:
e = np.array([[1,2,3,4],[3,4,5,6]])
e
e.shape

(2, 4)

In [8]:
# 배열의 원소 유형 확인하기 : dtype
#배열의 유형을 아는 것은 매우 중요합니다. 숫자로 되어 있으면연산을 할 수 있고, 문자로 되어 있으면 정규식을 사용할 수있습니다.
d.dtype

dtype('int32')

In [9]:
# 배열 유형 바꾸기 : astype()
data = np.arange(1,55)
data.dtype
data.astype('float64')
data.astype('int32')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54])

In [10]:
#넘파이 함수 알아보기
#0으로 이루어진 배열만들기
np.zeros((2,100))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [11]:
# 1로 이루어진 배열 만들기 : np.ones()
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
# 연속형 정수 생성하기 
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#행과 열 바꾸기
a=np.ones((2,3))
a
b=np.transpose(a)
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
#배열의 사칙연산

#배열의 덧셈
arr1 = np.array([[2,3,4],[6,7,8]])
arr2 = np.array([[12,23,14],[36,47,58]])

arr1+arr2

array([[14, 26, 18],
       [42, 54, 66]])

In [15]:
#배열의 곱셈
arr1* arr2

arr2-arr1

array([[10, 20, 10],
       [30, 40, 50]])

In [16]:
#배열의 나눗셈
arr2/arr1

array([[6.        , 7.66666667, 3.5       ],
       [6.        , 6.71428571, 7.25      ]])

In [17]:
#크기가 서로다른 배열끼리 더하기
arr3 = np.array([100,200,300])

arr1 + arr3

array([[102, 203, 304],
       [106, 207, 308]])

In [18]:
arr1.shape
arr3.shape

(3,)

In [19]:
arr4 = np.array([1,2,3,4,5,6,7,8,9,10])
arr4.shape

arr1 + arr4

ValueError: operands could not be broadcast together with shapes (2,3) (10,) 

In [ ]:
arr5 = ([[9],[3]])
arr1 + arr5

array([[11, 12, 13],
       [ 9, 10, 11]])

In [ ]:
# 파이썬 리스트와 배열의 차이점
# 생김세는 비슷 하지만 같은 자료형은 아니다.
d= np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]])
d_list = [[1,2,3,4,5],
          [2,4,5,6,7],
          [5,7,8,9,9]]